---
abstract: 'send a metric value to gmond with libganglia C library'
author:
  - 'HIROSE Masaaki, C<< <hirose@klab.org> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Ganglia-Gmetric-XS
no_index:
  directory:
    - inc
    - t
version: 1.00
